DROP SCHEMA IF EXISTS `copyOIC`;
CREATE SCHEMA IF NOT EXISTS `copyOIC`;
USE `copyOIC`;

DROP TABLE IF EXISTS `copyOIC`.`BASE_OIC2`;
CREATE TABLE IF NOT EXISTS `copyOIC`.`BASE_OIC2` (
	`CLIENTE` varchar(100) DEFAULT NULL,
	`NOMBRE` varchar(256) DEFAULT NULL,
	`VENDEDOR` varchar(50) DEFAULT NULL,
	`VENNOM` varchar(256) DEFAULT NULL,
	`U_SEGMENTO` varchar(256) DEFAULT NULL,
	`U_REGION_VTA` varchar(256) DEFAULT NULL,
	`U_AGRUPACION` varchar(256) DEFAULT NULL,
	`RUTA` varchar(256) DEFAULT NULL,
	`ZONA` varchar(256) DEFAULT NULL,
	`PROVINCIA` varchar(256) DEFAULT NULL,
	`CANTON` varchar(256) DEFAULT NULL,
	`DISTRITO` varchar(256) DEFAULT NULL,
	`PEDIDO` varchar(120) DEFAULT NULL,
	`MONEDA_FACTURA` varchar(2) DEFAULT NULL,
	`TIPO_CAMBIO` DECIMAL(38,8) DEFAULT NULL,
	`ARTICULO` varchar(256) DEFAULT NULL,
	`DESCRIPCION` varchar(256) DEFAULT NULL,
	`CLASIFICACION_1` varchar(256) DEFAULT NULL,
	`CLASIFICACION_1_DES` varchar(256) DEFAULT NULL,
	`CLASIFICACION_2` varchar(256) DEFAULT NULL,
	`CLASIFICACION_2_DES` varchar(256) DEFAULT NULL,
	`CLASIFICACION_3` varchar(256) DEFAULT NULL,
	`CLASIFICACION_3_DES` varchar(256) DEFAULT NULL,
	`CLASIFICACION_4` varchar(256) DEFAULT NULL,
	`CLASIFICACION_4_DES` varchar(256) DEFAULT NULL,
	`CLASIFICACION_5` varchar(256) DEFAULT NULL,
	`CLASIFICACION_5_DES` varchar(256) DEFAULT NULL,
	`FECHA` DATETIME(3) DEFAULT NULL,
	`CANTIDAD` DECIMAL(38,8) DEFAULT NULL,
	`VTAS` DECIMAL(38,8) DEFAULT NULL,
	`MARGEN` DECIMAL(38,8) DEFAULT NULL,
	`COSTO` DECIMAL(38,8) DEFAULT NULL
);

DROP TABLE IF EXISTS `copyOIC`.`CLIENTE_OIC`;
CREATE TABLE IF NOT EXISTS `copyOIC`.`CLIENTE_OIC` (
	`CLIENTE` varchar(50) DEFAULT NULL,
	`RAZON_SOCIAL` varchar(256) DEFAULT NULL,
	`PROVINCIA` varchar(256) DEFAULT NULL,
	`CANTON` varchar(256) DEFAULT NULL,
	`DISTRITO` varchar(256) DEFAULT NULL,
	`DIRECCION` varchar(256) DEFAULT NULL,
	`ZONA` varchar(256) DEFAULT NULL,
	`CODIGO_VENDEDOR` varchar(256) DEFAULT NULL,
	`REPRESENTANTE_VENTAS` varchar(256) DEFAULT NULL,
	`SECTOR_DESPACHO` varchar(256) DEFAULT NULL,
	`CONDICION_PAGO` INT(10) DEFAULT NULL
);

DROP TABLE IF EXISTS `copyOIC`.`OIC_VENDEDOR`;
CREATE TABLE IF NOT EXISTS `copyOIC`.`OIC_VENDEDOR` (
	`VENDEDOR` varchar(4) NOT NULL,
	`NOMBRE` varchar(40) NOT NULL,
	`E_MAIL` varchar(249) DEFAULT NULL,
	`ACTIVO` varchar(1) NOT NULL,
	`U_SUPERVISOR` varchar(150) DEFAULT NULL,
	`U_LOCALIDAD` varchar(150) DEFAULT NULL,
	`U_ROL` varchar(150) DEFAULT NULL
);

DROP TABLE IF EXISTS `copyOIC`.`clients`;
CREATE TABLE IF NOT EXISTS `copyOIC`.`clients` (
    `cli_id` int(11) NOT NULL AUTO_INCREMENT,
    `cli_name` varchar(45) NOT NULL,
    PRIMARY KEY (`cli_id`)
);

DROP TABLE IF EXISTS `copyOIC`.`users`;
CREATE TABLE IF NOT EXISTS `copyOIC`.`users` (
    `usr_id` int(11) NOT NULL AUTO_INCREMENT,
    `usr_name` varchar(45) DEFAULT NULL,
    `usr_last_name` varchar(45) DEFAULT NULL,
    `usr_email` varchar(200) DEFAULT NULL,
    `usr_rol` varchar(45) DEFAULT NULL,
    `usr_status` varchar(45) DEFAULT NULL,
    `cli_id` int(11) NOT NULL,
    PRIMARY KEY (`usr_id`),
    KEY `cli_id` (`cli_id`),
    CONSTRAINT `users_ibfk_1` FOREIGN KEY (`cli_id`) REFERENCES `copyOIC`.`clients` (`cli_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `copyOIC`.`habiles`;
CREATE TABLE IF NOT EXISTS `copyOIC`.`habiles` (
  `hbl_id` int(11) NOT NULL AUTO_INCREMENT,
  `hbl_date` date DEFAULT NULL,
  `hbl_holidays` json DEFAULT NULL,
  `hbl_days` varchar(50) DEFAULT '1',
  `hbl_habiles_5` date DEFAULT NULL,
  PRIMARY KEY (`hbl_id`)
);