SELECT 
 	cli.RAZON_SOCIAL AS 'Agrupación',
	(CASE
    	WHEN (SUM(ACUM.ABC)/(SELECT SUM(VTAS) AS TOTAL FROM base_oic2)) <=0.8 THEN 'A'
    	WHEN (SUM(ACUM.ABC)/(SELECT SUM(VTAS) AS TOTAL FROM base_oic2)) <=0.95 THEN 'B'
    	ELSE 'C'
	END) AS ABC
				
FROM 
	cliente_oic AS cli 
LEFT JOIN
	(SELECT NOMBRE, SUM(VTAS) AS ABC FROM base_oic2 GROUP BY NOMBRE) AS ABC_2
	ON ( cli.RAZON_SOCIAL = ABC_2.NOMBRE )
LEFT JOIN
	(SELECT NOMBRE, SUM(VTAS) AS ABC FROM base_oic2 GROUP BY NOMBRE) AS ACUM
	ON (ABC_2.ABC <= ACUM.ABC)
WHERE 
    ABC_2.ABC IS NOT NULL
GROUP BY  ABC_2.ABC, cli.RAZON_SOCIAL
ORDER BY cli.RAZON_SOCIAL
;