SELECT 
DISTINCT base.U_AGRUPACION,
base.ARTICULO,
base.CLASIFICACION_3_DES, 
base.DESCRIPCION, 
base4.Suma AS 'Col1',
base3.Suma AS 'Col2',
base2.Suma AS 'Col3',
base1.Suma AS 'Col4',
base.VENDEDOR AS 'Codigo Vendedor',
base.VENNOM AS 'Vendedor',
NOW() AS Date


FROM base_oic2 AS base

LEFT JOIN(
	SELECT 
		U_AGRUPACION,
		CLASIFICACION_3_DES,
		ARTICULO, DESCRIPCION,
		SUM(CASE WHEN VTAS < 0 THEN -1*CANTIDAD ELSE CANTIDAD END) AS Suma
	FROM base_oic2 
	WHERE MONTH(FECHA) = MONTH(DATE_ADD(NOW(), INTERVAL -1 MONTH)) AND U_AGRUPACION IS NOT NULL
	GROUP BY U_AGRUPACION, CLASIFICACION_3_DES, ARTICULO, DESCRIPCION
	ORDER BY U_AGRUPACION) AS base1
ON(base.U_AGRUPACION = base1.U_AGRUPACION AND base.ARTICULO = base1.ARTICULO )

LEFT JOIN(
	SELECT 
		U_AGRUPACION,
		CLASIFICACION_3_DES,
		ARTICULO, DESCRIPCION,
		SUM(CASE WHEN VTAS < 0 THEN -1*CANTIDAD ELSE CANTIDAD END) AS Suma
	FROM base_oic2 
	WHERE MONTH(FECHA) = MONTH(DATE_ADD(NOW(), INTERVAL -2 MONTH))  AND U_AGRUPACION IS NOT NULL
	GROUP BY U_AGRUPACION, CLASIFICACION_3_DES, ARTICULO, DESCRIPCION
	ORDER BY U_AGRUPACION) AS base2
ON(base.U_AGRUPACION = base2.U_AGRUPACION AND base.ARTICULO = base2.ARTICULO )

LEFT JOIN(
	SELECT 
		U_AGRUPACION,
		CLASIFICACION_3_DES,
		ARTICULO, DESCRIPCION,
		SUM(CASE WHEN VTAS < 0 THEN -1*CANTIDAD ELSE CANTIDAD END) AS Suma
	FROM base_oic2 
	WHERE MONTH(FECHA) = MONTH(DATE_ADD(NOW(), INTERVAL -3 MONTH))  AND U_AGRUPACION IS NOT NULL
	GROUP BY U_AGRUPACION, CLASIFICACION_3_DES, ARTICULO, DESCRIPCION
	ORDER BY U_AGRUPACION) AS base3
ON(base.U_AGRUPACION = base3.U_AGRUPACION AND base.ARTICULO = base3.ARTICULO )

LEFT JOIN(
	SELECT 
		U_AGRUPACION,
		CLASIFICACION_3_DES,
		ARTICULO, DESCRIPCION,
		SUM(CASE WHEN VTAS < 0 THEN -1*CANTIDAD ELSE CANTIDAD END) AS Suma
	FROM base_oic2 
	WHERE MONTH(FECHA) = MONTH(DATE_ADD(NOW(), INTERVAL -4 MONTH))  AND U_AGRUPACION IS NOT NULL
	GROUP BY U_AGRUPACION, CLASIFICACION_3_DES, ARTICULO, DESCRIPCION
	ORDER BY U_AGRUPACION) AS base4
ON(base.U_AGRUPACION = base4.U_AGRUPACION AND base.ARTICULO = base4.ARTICULO )

WHERE 
	base.U_AGRUPACION IS NOT NULL AND NOT(base1.Suma IS NULL AND base2.Suma IS NULL AND base3.Suma IS NULL AND base4.Suma IS NULL)
ORDER BY 
	base.U_AGRUPACION, 
	base.CLASIFICACION_3_DES, 
	base.DESCRIPCION;